/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * MapaCurricular.java
 *
 * Created on 13-may-2012, 13:40:07
 */
package linx;

/**
 *
 * @author DELL
 */
public class MapaCurricular extends javax.swing.JFrame {

    /** Creates new form MapaCurricular */
    public MapaCurricular() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane39 = new javax.swing.JLayeredPane();
        jLayeredPane38 = new javax.swing.JLayeredPane();
        jScrollPane9 = new javax.swing.JScrollPane();
        txtmat11 = new javax.swing.JTextPane();
        jScrollPane10 = new javax.swing.JScrollPane();
        txtmat12 = new javax.swing.JTextPane();
        jScrollPane11 = new javax.swing.JScrollPane();
        txtmat13 = new javax.swing.JTextPane();
        jScrollPane12 = new javax.swing.JScrollPane();
        txtmat14 = new javax.swing.JTextPane();
        jScrollPane13 = new javax.swing.JScrollPane();
        txtmat15 = new javax.swing.JTextPane();
        jScrollPane14 = new javax.swing.JScrollPane();
        txtmat16 = new javax.swing.JTextPane();
        jScrollPane15 = new javax.swing.JScrollPane();
        txtmat17 = new javax.swing.JTextPane();
        jScrollPane16 = new javax.swing.JScrollPane();
        jTextPane5 = new javax.swing.JTextPane();
        jScrollPane17 = new javax.swing.JScrollPane();
        jTextPane6 = new javax.swing.JTextPane();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTextPane7 = new javax.swing.JTextPane();
        jScrollPane19 = new javax.swing.JScrollPane();
        jTextPane8 = new javax.swing.JTextPane();
        jScrollPane22 = new javax.swing.JScrollPane();
        txtmat21 = new javax.swing.JTextPane();
        jScrollPane23 = new javax.swing.JScrollPane();
        txtmat22 = new javax.swing.JTextPane();
        jScrollPane24 = new javax.swing.JScrollPane();
        txtmat23 = new javax.swing.JTextPane();
        jScrollPane25 = new javax.swing.JScrollPane();
        txtmat24 = new javax.swing.JTextPane();
        jScrollPane26 = new javax.swing.JScrollPane();
        txtmat25 = new javax.swing.JTextPane();
        jScrollPane27 = new javax.swing.JScrollPane();
        txtmat26 = new javax.swing.JTextPane();
        jScrollPane28 = new javax.swing.JScrollPane();
        txtmat27 = new javax.swing.JTextPane();
        jScrollPane29 = new javax.swing.JScrollPane();
        txtmat31 = new javax.swing.JTextPane();
        jScrollPane30 = new javax.swing.JScrollPane();
        txtmat32 = new javax.swing.JTextPane();
        jScrollPane31 = new javax.swing.JScrollPane();
        txtmat33 = new javax.swing.JTextPane();
        jScrollPane32 = new javax.swing.JScrollPane();
        txtmat34 = new javax.swing.JTextPane();
        jScrollPane33 = new javax.swing.JScrollPane();
        txtmat35 = new javax.swing.JTextPane();
        jScrollPane34 = new javax.swing.JScrollPane();
        txtmat36 = new javax.swing.JTextPane();
        jScrollPane35 = new javax.swing.JScrollPane();
        txtmat37 = new javax.swing.JTextPane();
        jScrollPane36 = new javax.swing.JScrollPane();
        txtmat41 = new javax.swing.JTextPane();
        jScrollPane37 = new javax.swing.JScrollPane();
        txtmat42 = new javax.swing.JTextPane();
        jScrollPane38 = new javax.swing.JScrollPane();
        txtmat43 = new javax.swing.JTextPane();
        jScrollPane39 = new javax.swing.JScrollPane();
        txtmat44 = new javax.swing.JTextPane();
        jScrollPane40 = new javax.swing.JScrollPane();
        txtmat45 = new javax.swing.JTextPane();
        jScrollPane41 = new javax.swing.JScrollPane();
        txtmat46 = new javax.swing.JTextPane();
        jScrollPane42 = new javax.swing.JScrollPane();
        txtmat47 = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jScrollPane43 = new javax.swing.JScrollPane();
        txtmat51 = new javax.swing.JTextPane();
        jScrollPane44 = new javax.swing.JScrollPane();
        txtmat52 = new javax.swing.JTextPane();
        jScrollPane45 = new javax.swing.JScrollPane();
        txtmat53 = new javax.swing.JTextPane();
        jScrollPane46 = new javax.swing.JScrollPane();
        txtmat54 = new javax.swing.JTextPane();
        jScrollPane47 = new javax.swing.JScrollPane();
        txtmat55 = new javax.swing.JTextPane();
        jScrollPane48 = new javax.swing.JScrollPane();
        txtmat56 = new javax.swing.JTextPane();
        jScrollPane49 = new javax.swing.JScrollPane();
        txtmat57 = new javax.swing.JTextPane();
        jScrollPane20 = new javax.swing.JScrollPane();
        jTextPane9 = new javax.swing.JTextPane();
        jScrollPane21 = new javax.swing.JScrollPane();
        jTextPane10 = new javax.swing.JTextPane();
        jScrollPane50 = new javax.swing.JScrollPane();
        jTextPane11 = new javax.swing.JTextPane();
        jScrollPane51 = new javax.swing.JScrollPane();
        jTextPane12 = new javax.swing.JTextPane();
        jScrollPane52 = new javax.swing.JScrollPane();
        jTextPane13 = new javax.swing.JTextPane();
        jScrollPane53 = new javax.swing.JScrollPane();
        txtmat61 = new javax.swing.JTextPane();
        jScrollPane54 = new javax.swing.JScrollPane();
        txtmat71 = new javax.swing.JTextPane();
        jScrollPane55 = new javax.swing.JScrollPane();
        txtmat81 = new javax.swing.JTextPane();
        jScrollPane56 = new javax.swing.JScrollPane();
        txtmat91 = new javax.swing.JTextPane();
        jScrollPane57 = new javax.swing.JScrollPane();
        txtmat62 = new javax.swing.JTextPane();
        jScrollPane58 = new javax.swing.JScrollPane();
        txtmat63 = new javax.swing.JTextPane();
        jScrollPane59 = new javax.swing.JScrollPane();
        txtmat64 = new javax.swing.JTextPane();
        jScrollPane60 = new javax.swing.JScrollPane();
        txtmat65 = new javax.swing.JTextPane();
        jScrollPane61 = new javax.swing.JScrollPane();
        txtmat66 = new javax.swing.JTextPane();
        jScrollPane62 = new javax.swing.JScrollPane();
        txtmat67 = new javax.swing.JTextPane();
        jScrollPane63 = new javax.swing.JScrollPane();
        txtmat72 = new javax.swing.JTextPane();
        jScrollPane64 = new javax.swing.JScrollPane();
        txtmat73 = new javax.swing.JTextPane();
        jScrollPane65 = new javax.swing.JScrollPane();
        txtmat74 = new javax.swing.JTextPane();
        jScrollPane66 = new javax.swing.JScrollPane();
        txtmat75 = new javax.swing.JTextPane();
        jScrollPane67 = new javax.swing.JScrollPane();
        txtmat76 = new javax.swing.JTextPane();
        jScrollPane68 = new javax.swing.JScrollPane();
        txtmat77 = new javax.swing.JTextPane();
        jScrollPane69 = new javax.swing.JScrollPane();
        txtmat82 = new javax.swing.JTextPane();
        jScrollPane70 = new javax.swing.JScrollPane();
        txtmat83 = new javax.swing.JTextPane();
        jScrollPane71 = new javax.swing.JScrollPane();
        txtmat84 = new javax.swing.JTextPane();
        jScrollPane72 = new javax.swing.JScrollPane();
        txtmat85 = new javax.swing.JTextPane();
        jScrollPane73 = new javax.swing.JScrollPane();
        txtmat86 = new javax.swing.JTextPane();
        jScrollPane74 = new javax.swing.JScrollPane();
        txtmat87 = new javax.swing.JTextPane();
        jScrollPane75 = new javax.swing.JScrollPane();
        txtmat92 = new javax.swing.JTextPane();
        jScrollPane76 = new javax.swing.JScrollPane();
        txtmat93 = new javax.swing.JTextPane();
        jScrollPane77 = new javax.swing.JScrollPane();
        txtmat94 = new javax.swing.JTextPane();
        jScrollPane78 = new javax.swing.JScrollPane();
        txtmat95 = new javax.swing.JTextPane();
        jScrollPane79 = new javax.swing.JScrollPane();
        txtmat96 = new javax.swing.JTextPane();
        jScrollPane80 = new javax.swing.JScrollPane();
        txtmat97 = new javax.swing.JTextPane();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLayeredPane40 = new javax.swing.JLayeredPane();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        apematalu5 = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        apepatalu5 = new javax.swing.JTextField();
        nomalu5 = new javax.swing.JTextField();
        ctaalu5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLayeredPane39.setBorder(javax.swing.BorderFactory.createTitledBorder("Mapa  Curricular"));

        jLayeredPane38.setBorder(javax.swing.BorderFactory.createTitledBorder("Estado de Materias"));
        jLayeredPane38.setBounds(370, 20, 350, 110);
        jLayeredPane39.add(jLayeredPane38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane9.setBackground(new java.awt.Color(255, 51, 51));

        txtmat11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat11.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane9.setViewportView(txtmat11);

        jScrollPane9.setBounds(40, 140, 100, 50);
        jLayeredPane39.add(jScrollPane9, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane10.setBackground(new java.awt.Color(255, 51, 51));

        txtmat12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat12.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane10.setViewportView(txtmat12);

        jScrollPane10.setBounds(140, 140, 100, 50);
        jLayeredPane39.add(jScrollPane10, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane11.setBackground(new java.awt.Color(255, 51, 51));

        txtmat13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat13.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane11.setViewportView(txtmat13);

        jScrollPane11.setBounds(240, 140, 100, 50);
        jLayeredPane39.add(jScrollPane11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane12.setBackground(new java.awt.Color(255, 51, 51));

        txtmat14.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat14.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane12.setViewportView(txtmat14);

        jScrollPane12.setBounds(340, 140, 100, 50);
        jLayeredPane39.add(jScrollPane12, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane13.setBackground(new java.awt.Color(255, 51, 51));

        txtmat15.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat15.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane13.setViewportView(txtmat15);

        jScrollPane13.setBounds(440, 140, 100, 50);
        jLayeredPane39.add(jScrollPane13, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane14.setBackground(new java.awt.Color(255, 51, 51));

        txtmat16.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat16.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane14.setViewportView(txtmat16);

        jScrollPane14.setBounds(540, 140, 100, 50);
        jLayeredPane39.add(jScrollPane14, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane15.setBackground(new java.awt.Color(255, 51, 51));

        txtmat17.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat17.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane15.setViewportView(txtmat17);

        jScrollPane15.setBounds(640, 140, 100, 50);
        jLayeredPane39.add(jScrollPane15, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane16.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane5.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane5.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane5.setText("1");
        jScrollPane16.setViewportView(jTextPane5);

        jScrollPane16.setBounds(10, 140, 30, 50);
        jLayeredPane39.add(jScrollPane16, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane17.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane6.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane6.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane6.setText("2");
        jScrollPane17.setViewportView(jTextPane6);

        jScrollPane17.setBounds(10, 190, 30, 50);
        jLayeredPane39.add(jScrollPane17, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane18.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane7.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane7.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane7.setText("3");
        jScrollPane18.setViewportView(jTextPane7);

        jScrollPane18.setBounds(10, 240, 30, 50);
        jLayeredPane39.add(jScrollPane18, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane19.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane8.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane8.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane8.setText("9");
        jScrollPane19.setViewportView(jTextPane8);

        jScrollPane19.setBounds(10, 540, 30, 50);
        jLayeredPane39.add(jScrollPane19, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane22.setBackground(new java.awt.Color(255, 51, 51));

        txtmat21.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat21.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane22.setViewportView(txtmat21);

        jScrollPane22.setBounds(40, 190, 100, 50);
        jLayeredPane39.add(jScrollPane22, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane23.setBackground(new java.awt.Color(255, 51, 51));

        txtmat22.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat22.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane23.setViewportView(txtmat22);

        jScrollPane23.setBounds(140, 190, 100, 50);
        jLayeredPane39.add(jScrollPane23, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane24.setBackground(new java.awt.Color(255, 51, 51));

        txtmat23.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat23.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane24.setViewportView(txtmat23);

        jScrollPane24.setBounds(240, 190, 100, 50);
        jLayeredPane39.add(jScrollPane24, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane25.setBackground(new java.awt.Color(255, 51, 51));

        txtmat24.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat24.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane25.setViewportView(txtmat24);

        jScrollPane25.setBounds(340, 190, 100, 50);
        jLayeredPane39.add(jScrollPane25, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane26.setBackground(new java.awt.Color(255, 51, 51));

        txtmat25.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat25.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane26.setViewportView(txtmat25);

        jScrollPane26.setBounds(440, 190, 100, 50);
        jLayeredPane39.add(jScrollPane26, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane27.setBackground(new java.awt.Color(255, 51, 51));

        txtmat26.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat26.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane27.setViewportView(txtmat26);

        jScrollPane27.setBounds(540, 190, 100, 50);
        jLayeredPane39.add(jScrollPane27, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane28.setBackground(new java.awt.Color(255, 51, 51));

        txtmat27.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat27.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane28.setViewportView(txtmat27);

        jScrollPane28.setBounds(640, 190, 100, 50);
        jLayeredPane39.add(jScrollPane28, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane29.setBackground(new java.awt.Color(255, 51, 51));

        txtmat31.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat31.setFont(new java.awt.Font("Arial", 0, 8)); // NOI18N
        jScrollPane29.setViewportView(txtmat31);

        jScrollPane29.setBounds(40, 240, 100, 50);
        jLayeredPane39.add(jScrollPane29, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane30.setBackground(new java.awt.Color(255, 51, 51));

        txtmat32.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat32.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane30.setViewportView(txtmat32);

        jScrollPane30.setBounds(140, 240, 100, 50);
        jLayeredPane39.add(jScrollPane30, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane31.setBackground(new java.awt.Color(255, 51, 51));

        txtmat33.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat33.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane31.setViewportView(txtmat33);

        jScrollPane31.setBounds(240, 240, 100, 50);
        jLayeredPane39.add(jScrollPane31, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane32.setBackground(new java.awt.Color(255, 51, 51));

        txtmat34.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat34.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane32.setViewportView(txtmat34);

        jScrollPane32.setBounds(340, 240, 100, 50);
        jLayeredPane39.add(jScrollPane32, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane33.setBackground(new java.awt.Color(255, 51, 51));

        txtmat35.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat35.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane33.setViewportView(txtmat35);

        jScrollPane33.setBounds(440, 240, 100, 50);
        jLayeredPane39.add(jScrollPane33, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane34.setBackground(new java.awt.Color(255, 51, 51));

        txtmat36.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat36.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane34.setViewportView(txtmat36);

        jScrollPane34.setBounds(540, 240, 100, 50);
        jLayeredPane39.add(jScrollPane34, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane35.setBackground(new java.awt.Color(255, 51, 51));

        txtmat37.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat37.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane35.setViewportView(txtmat37);

        jScrollPane35.setBounds(640, 240, 100, 50);
        jLayeredPane39.add(jScrollPane35, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane36.setBackground(new java.awt.Color(255, 51, 51));

        txtmat41.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat41.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane36.setViewportView(txtmat41);

        jScrollPane36.setBounds(40, 290, 100, 50);
        jLayeredPane39.add(jScrollPane36, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane37.setBackground(new java.awt.Color(255, 51, 51));

        txtmat42.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat42.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane37.setViewportView(txtmat42);

        jScrollPane37.setBounds(140, 290, 100, 50);
        jLayeredPane39.add(jScrollPane37, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane38.setBackground(new java.awt.Color(255, 51, 51));

        txtmat43.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat43.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane38.setViewportView(txtmat43);

        jScrollPane38.setBounds(240, 290, 100, 50);
        jLayeredPane39.add(jScrollPane38, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane39.setBackground(new java.awt.Color(255, 51, 51));

        txtmat44.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat44.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane39.setViewportView(txtmat44);

        jScrollPane39.setBounds(340, 290, 100, 50);
        jLayeredPane39.add(jScrollPane39, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane40.setBackground(new java.awt.Color(255, 51, 51));

        txtmat45.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat45.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane40.setViewportView(txtmat45);

        jScrollPane40.setBounds(440, 290, 100, 50);
        jLayeredPane39.add(jScrollPane40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane41.setBackground(new java.awt.Color(255, 51, 51));

        txtmat46.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat46.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane41.setViewportView(txtmat46);

        jScrollPane41.setBounds(540, 290, 100, 50);
        jLayeredPane39.add(jScrollPane41, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane42.setBackground(new java.awt.Color(255, 51, 51));

        txtmat47.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat47.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane42.setViewportView(txtmat47);

        jScrollPane42.setBounds(640, 290, 100, 50);
        jLayeredPane39.add(jScrollPane42, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jButton1.setText("Cerrar Ventana");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jButton1MouseReleased(evt);
            }
        });
        jButton1.setBounds(230, 610, 250, 23);
        jLayeredPane39.add(jButton1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane43.setBackground(new java.awt.Color(255, 51, 51));

        txtmat51.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat51.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane43.setViewportView(txtmat51);

        jScrollPane43.setBounds(40, 340, 100, 50);
        jLayeredPane39.add(jScrollPane43, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane44.setBackground(new java.awt.Color(255, 51, 51));

        txtmat52.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat52.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane44.setViewportView(txtmat52);

        jScrollPane44.setBounds(140, 340, 100, 50);
        jLayeredPane39.add(jScrollPane44, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane45.setBackground(new java.awt.Color(255, 51, 51));

        txtmat53.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat53.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane45.setViewportView(txtmat53);

        jScrollPane45.setBounds(240, 340, 100, 50);
        jLayeredPane39.add(jScrollPane45, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane46.setBackground(new java.awt.Color(255, 51, 51));

        txtmat54.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat54.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane46.setViewportView(txtmat54);

        jScrollPane46.setBounds(340, 340, 100, 50);
        jLayeredPane39.add(jScrollPane46, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane47.setBackground(new java.awt.Color(255, 51, 51));

        txtmat55.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat55.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane47.setViewportView(txtmat55);

        jScrollPane47.setBounds(440, 340, 100, 50);
        jLayeredPane39.add(jScrollPane47, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane48.setBackground(new java.awt.Color(255, 51, 51));

        txtmat56.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat56.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane48.setViewportView(txtmat56);

        jScrollPane48.setBounds(540, 340, 100, 50);
        jLayeredPane39.add(jScrollPane48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane49.setBackground(new java.awt.Color(255, 51, 51));

        txtmat57.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat57.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane49.setViewportView(txtmat57);

        jScrollPane49.setBounds(640, 340, 100, 50);
        jLayeredPane39.add(jScrollPane49, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane20.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane9.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane9.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane9.setText("4");
        jScrollPane20.setViewportView(jTextPane9);

        jScrollPane20.setBounds(10, 290, 30, 50);
        jLayeredPane39.add(jScrollPane20, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane21.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane10.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane10.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane10.setText("5");
        jScrollPane21.setViewportView(jTextPane10);

        jScrollPane21.setBounds(10, 340, 30, 50);
        jLayeredPane39.add(jScrollPane21, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane50.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane11.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane11.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane11.setText("6");
        jScrollPane50.setViewportView(jTextPane11);

        jScrollPane50.setBounds(10, 390, 30, 50);
        jLayeredPane39.add(jScrollPane50, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane51.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane12.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane12.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane12.setText("7");
        jScrollPane51.setViewportView(jTextPane12);

        jScrollPane51.setBounds(10, 440, 30, 50);
        jLayeredPane39.add(jScrollPane51, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane52.setBackground(new java.awt.Color(255, 51, 51));

        jTextPane13.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextPane13.setFont(new java.awt.Font("Arial", 0, 36));
        jTextPane13.setText("8");
        jScrollPane52.setViewportView(jTextPane13);

        jScrollPane52.setBounds(10, 490, 30, 50);
        jLayeredPane39.add(jScrollPane52, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane53.setBackground(new java.awt.Color(255, 51, 51));

        txtmat61.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat61.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane53.setViewportView(txtmat61);

        jScrollPane53.setBounds(40, 390, 100, 50);
        jLayeredPane39.add(jScrollPane53, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane54.setBackground(new java.awt.Color(255, 51, 51));

        txtmat71.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat71.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane54.setViewportView(txtmat71);

        jScrollPane54.setBounds(40, 440, 100, 50);
        jLayeredPane39.add(jScrollPane54, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane55.setBackground(new java.awt.Color(255, 51, 51));

        txtmat81.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat81.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane55.setViewportView(txtmat81);

        jScrollPane55.setBounds(40, 490, 100, 50);
        jLayeredPane39.add(jScrollPane55, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane56.setBackground(new java.awt.Color(255, 51, 51));

        txtmat91.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat91.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane56.setViewportView(txtmat91);

        jScrollPane56.setBounds(40, 540, 100, 50);
        jLayeredPane39.add(jScrollPane56, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane57.setBackground(new java.awt.Color(255, 51, 51));

        txtmat62.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat62.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane57.setViewportView(txtmat62);

        jScrollPane57.setBounds(140, 390, 100, 50);
        jLayeredPane39.add(jScrollPane57, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane58.setBackground(new java.awt.Color(255, 51, 51));

        txtmat63.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat63.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane58.setViewportView(txtmat63);

        jScrollPane58.setBounds(240, 390, 100, 50);
        jLayeredPane39.add(jScrollPane58, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane59.setBackground(new java.awt.Color(255, 51, 51));

        txtmat64.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat64.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane59.setViewportView(txtmat64);

        jScrollPane59.setBounds(340, 390, 100, 50);
        jLayeredPane39.add(jScrollPane59, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane60.setBackground(new java.awt.Color(255, 51, 51));

        txtmat65.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat65.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane60.setViewportView(txtmat65);

        jScrollPane60.setBounds(440, 390, 100, 50);
        jLayeredPane39.add(jScrollPane60, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane61.setBackground(new java.awt.Color(255, 51, 51));

        txtmat66.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat66.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane61.setViewportView(txtmat66);

        jScrollPane61.setBounds(540, 390, 100, 50);
        jLayeredPane39.add(jScrollPane61, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane62.setBackground(new java.awt.Color(255, 51, 51));

        txtmat67.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat67.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane62.setViewportView(txtmat67);

        jScrollPane62.setBounds(640, 390, 100, 50);
        jLayeredPane39.add(jScrollPane62, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane63.setBackground(new java.awt.Color(255, 51, 51));

        txtmat72.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat72.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane63.setViewportView(txtmat72);

        jScrollPane63.setBounds(140, 440, 100, 50);
        jLayeredPane39.add(jScrollPane63, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane64.setBackground(new java.awt.Color(255, 51, 51));

        txtmat73.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat73.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane64.setViewportView(txtmat73);

        jScrollPane64.setBounds(240, 440, 100, 50);
        jLayeredPane39.add(jScrollPane64, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane65.setBackground(new java.awt.Color(255, 51, 51));

        txtmat74.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat74.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane65.setViewportView(txtmat74);

        jScrollPane65.setBounds(340, 440, 100, 50);
        jLayeredPane39.add(jScrollPane65, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane66.setBackground(new java.awt.Color(255, 51, 51));

        txtmat75.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat75.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane66.setViewportView(txtmat75);

        jScrollPane66.setBounds(440, 440, 100, 50);
        jLayeredPane39.add(jScrollPane66, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane67.setBackground(new java.awt.Color(255, 51, 51));

        txtmat76.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat76.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane67.setViewportView(txtmat76);

        jScrollPane67.setBounds(540, 440, 100, 50);
        jLayeredPane39.add(jScrollPane67, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane68.setBackground(new java.awt.Color(255, 51, 51));

        txtmat77.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat77.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane68.setViewportView(txtmat77);

        jScrollPane68.setBounds(640, 440, 100, 50);
        jLayeredPane39.add(jScrollPane68, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane69.setBackground(new java.awt.Color(255, 51, 51));

        txtmat82.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat82.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane69.setViewportView(txtmat82);

        jScrollPane69.setBounds(140, 490, 100, 50);
        jLayeredPane39.add(jScrollPane69, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane70.setBackground(new java.awt.Color(255, 51, 51));

        txtmat83.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat83.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane70.setViewportView(txtmat83);

        jScrollPane70.setBounds(240, 490, 100, 50);
        jLayeredPane39.add(jScrollPane70, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane71.setBackground(new java.awt.Color(255, 51, 51));

        txtmat84.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat84.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane71.setViewportView(txtmat84);

        jScrollPane71.setBounds(340, 490, 100, 50);
        jLayeredPane39.add(jScrollPane71, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane72.setBackground(new java.awt.Color(255, 51, 51));

        txtmat85.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat85.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane72.setViewportView(txtmat85);

        jScrollPane72.setBounds(440, 490, 100, 50);
        jLayeredPane39.add(jScrollPane72, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane73.setBackground(new java.awt.Color(255, 51, 51));

        txtmat86.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat86.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane73.setViewportView(txtmat86);

        jScrollPane73.setBounds(540, 490, 100, 50);
        jLayeredPane39.add(jScrollPane73, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane74.setBackground(new java.awt.Color(255, 51, 51));

        txtmat87.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat87.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane74.setViewportView(txtmat87);

        jScrollPane74.setBounds(640, 490, 100, 50);
        jLayeredPane39.add(jScrollPane74, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane75.setBackground(new java.awt.Color(255, 51, 51));

        txtmat92.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat92.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane75.setViewportView(txtmat92);

        jScrollPane75.setBounds(140, 540, 100, 50);
        jLayeredPane39.add(jScrollPane75, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane76.setBackground(new java.awt.Color(255, 51, 51));

        txtmat93.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat93.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane76.setViewportView(txtmat93);

        jScrollPane76.setBounds(240, 540, 100, 50);
        jLayeredPane39.add(jScrollPane76, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane77.setBackground(new java.awt.Color(255, 51, 51));

        txtmat94.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat94.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane77.setViewportView(txtmat94);

        jScrollPane77.setBounds(340, 540, 100, 50);
        jLayeredPane39.add(jScrollPane77, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane78.setBackground(new java.awt.Color(255, 51, 51));

        txtmat95.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat95.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane78.setViewportView(txtmat95);

        jScrollPane78.setBounds(440, 540, 100, 50);
        jLayeredPane39.add(jScrollPane78, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane79.setBackground(new java.awt.Color(255, 51, 51));

        txtmat96.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat96.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane79.setViewportView(txtmat96);

        jScrollPane79.setBounds(540, 540, 100, 50);
        jLayeredPane39.add(jScrollPane79, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jScrollPane80.setBackground(new java.awt.Color(255, 51, 51));

        txtmat97.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txtmat97.setFont(new java.awt.Font("Arial", 0, 8));
        jScrollPane80.setViewportView(txtmat97);

        jScrollPane80.setBounds(640, 540, 100, 50);
        jLayeredPane39.add(jScrollPane80, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField1.setBackground(new java.awt.Color(153, 153, 255));
        jTextField1.setForeground(new java.awt.Color(153, 153, 153));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jTextField1.setBounds(660, 80, 30, 30);
        jLayeredPane39.add(jTextField1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField2.setBackground(new java.awt.Color(255, 255, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 0));
        jTextField2.setBounds(660, 40, 30, 30);
        jLayeredPane39.add(jTextField2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel1.setText("Materias que se cursan ACTUALMENTE.");
        jLabel1.setBounds(460, 90, 230, 20);
        jLayeredPane39.add(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel2.setText("Materias Reprobadas.");
        jLabel2.setBounds(550, 50, 110, 20);
        jLayeredPane39.add(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setText("Materias Acreditadas.");
        jLabel3.setBounds(390, 50, 120, 20);
        jLayeredPane39.add(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTextField3.setBackground(new java.awt.Color(51, 153, 0));
        jTextField3.setForeground(new java.awt.Color(51, 153, 0));
        jTextField3.setBounds(500, 50, 30, 30);
        jLayeredPane39.add(jTextField3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane40.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos del Alumno"));

        jLabel47.setBackground(new java.awt.Color(204, 204, 255));
        jLabel47.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel47.setText("Nombre:");
        jLabel47.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel47.setOpaque(true);
        jLabel47.setBounds(10, 40, 120, 22);
        jLayeredPane40.add(jLabel47, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel48.setBackground(new java.awt.Color(204, 204, 255));
        jLabel48.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel48.setText("Apellido Materno");
        jLabel48.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel48.setOpaque(true);
        jLabel48.setBounds(10, 80, 120, 22);
        jLayeredPane40.add(jLabel48, javax.swing.JLayeredPane.DEFAULT_LAYER);

        apematalu5.setEditable(false);
        apematalu5.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        apematalu5.setBounds(130, 80, 200, 20);
        jLayeredPane40.add(apematalu5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel52.setBackground(new java.awt.Color(204, 204, 255));
        jLabel52.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel52.setText("Apellido Paterno:");
        jLabel52.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel52.setOpaque(true);
        jLabel52.setBounds(10, 60, 120, 22);
        jLayeredPane40.add(jLabel52, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel53.setBackground(new java.awt.Color(204, 204, 255));
        jLabel53.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        jLabel53.setText("Número de Cuenta:");
        jLabel53.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jLabel53.setOpaque(true);
        jLabel53.setBounds(10, 20, 120, 22);
        jLayeredPane40.add(jLabel53, javax.swing.JLayeredPane.DEFAULT_LAYER);

        apepatalu5.setEditable(false);
        apepatalu5.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        apepatalu5.setBounds(130, 60, 200, 20);
        jLayeredPane40.add(apepatalu5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        nomalu5.setEditable(false);
        nomalu5.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        nomalu5.setBounds(130, 40, 200, 20);
        jLayeredPane40.add(nomalu5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        ctaalu5.setEditable(false);
        ctaalu5.setFont(new java.awt.Font("Comic Sans MS", 0, 12));
        ctaalu5.setBounds(130, 20, 200, 20);
        jLayeredPane40.add(ctaalu5, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredPane40.setBounds(10, 20, 340, 110);
        jLayeredPane39.add(jLayeredPane40, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(jLayeredPane39, javax.swing.GroupLayout.PREFERRED_SIZE, 645, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseReleased

        // TODO add your handling code here:
		this.setVisible(false);
		}//GEN-LAST:event_jButton1MouseReleased

        private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed

        // TODO add your handling code here:
		}//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MapaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MapaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MapaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MapaCurricular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MapaCurricular().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField apematalu5;
    private javax.swing.JTextField apepatalu5;
    private javax.swing.JTextField ctaalu5;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLayeredPane jLayeredPane38;
    private javax.swing.JLayeredPane jLayeredPane39;
    private javax.swing.JLayeredPane jLayeredPane40;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane24;
    private javax.swing.JScrollPane jScrollPane25;
    private javax.swing.JScrollPane jScrollPane26;
    private javax.swing.JScrollPane jScrollPane27;
    private javax.swing.JScrollPane jScrollPane28;
    private javax.swing.JScrollPane jScrollPane29;
    private javax.swing.JScrollPane jScrollPane30;
    private javax.swing.JScrollPane jScrollPane31;
    private javax.swing.JScrollPane jScrollPane32;
    private javax.swing.JScrollPane jScrollPane33;
    private javax.swing.JScrollPane jScrollPane34;
    private javax.swing.JScrollPane jScrollPane35;
    private javax.swing.JScrollPane jScrollPane36;
    private javax.swing.JScrollPane jScrollPane37;
    private javax.swing.JScrollPane jScrollPane38;
    private javax.swing.JScrollPane jScrollPane39;
    private javax.swing.JScrollPane jScrollPane40;
    private javax.swing.JScrollPane jScrollPane41;
    private javax.swing.JScrollPane jScrollPane42;
    private javax.swing.JScrollPane jScrollPane43;
    private javax.swing.JScrollPane jScrollPane44;
    private javax.swing.JScrollPane jScrollPane45;
    private javax.swing.JScrollPane jScrollPane46;
    private javax.swing.JScrollPane jScrollPane47;
    private javax.swing.JScrollPane jScrollPane48;
    private javax.swing.JScrollPane jScrollPane49;
    private javax.swing.JScrollPane jScrollPane50;
    private javax.swing.JScrollPane jScrollPane51;
    private javax.swing.JScrollPane jScrollPane52;
    private javax.swing.JScrollPane jScrollPane53;
    private javax.swing.JScrollPane jScrollPane54;
    private javax.swing.JScrollPane jScrollPane55;
    private javax.swing.JScrollPane jScrollPane56;
    private javax.swing.JScrollPane jScrollPane57;
    private javax.swing.JScrollPane jScrollPane58;
    private javax.swing.JScrollPane jScrollPane59;
    private javax.swing.JScrollPane jScrollPane60;
    private javax.swing.JScrollPane jScrollPane61;
    private javax.swing.JScrollPane jScrollPane62;
    private javax.swing.JScrollPane jScrollPane63;
    private javax.swing.JScrollPane jScrollPane64;
    private javax.swing.JScrollPane jScrollPane65;
    private javax.swing.JScrollPane jScrollPane66;
    private javax.swing.JScrollPane jScrollPane67;
    private javax.swing.JScrollPane jScrollPane68;
    private javax.swing.JScrollPane jScrollPane69;
    private javax.swing.JScrollPane jScrollPane70;
    private javax.swing.JScrollPane jScrollPane71;
    private javax.swing.JScrollPane jScrollPane72;
    private javax.swing.JScrollPane jScrollPane73;
    private javax.swing.JScrollPane jScrollPane74;
    private javax.swing.JScrollPane jScrollPane75;
    private javax.swing.JScrollPane jScrollPane76;
    private javax.swing.JScrollPane jScrollPane77;
    private javax.swing.JScrollPane jScrollPane78;
    private javax.swing.JScrollPane jScrollPane79;
    private javax.swing.JScrollPane jScrollPane80;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextPane jTextPane10;
    private javax.swing.JTextPane jTextPane11;
    private javax.swing.JTextPane jTextPane12;
    private javax.swing.JTextPane jTextPane13;
    private javax.swing.JTextPane jTextPane5;
    private javax.swing.JTextPane jTextPane6;
    private javax.swing.JTextPane jTextPane7;
    private javax.swing.JTextPane jTextPane8;
    private javax.swing.JTextPane jTextPane9;
    private javax.swing.JTextField nomalu5;
    private javax.swing.JTextPane txtmat11;
    private javax.swing.JTextPane txtmat12;
    private javax.swing.JTextPane txtmat13;
    private javax.swing.JTextPane txtmat14;
    private javax.swing.JTextPane txtmat15;
    private javax.swing.JTextPane txtmat16;
    private javax.swing.JTextPane txtmat17;
    private javax.swing.JTextPane txtmat21;
    private javax.swing.JTextPane txtmat22;
    private javax.swing.JTextPane txtmat23;
    private javax.swing.JTextPane txtmat24;
    private javax.swing.JTextPane txtmat25;
    private javax.swing.JTextPane txtmat26;
    private javax.swing.JTextPane txtmat27;
    private javax.swing.JTextPane txtmat31;
    private javax.swing.JTextPane txtmat32;
    private javax.swing.JTextPane txtmat33;
    private javax.swing.JTextPane txtmat34;
    private javax.swing.JTextPane txtmat35;
    private javax.swing.JTextPane txtmat36;
    private javax.swing.JTextPane txtmat37;
    private javax.swing.JTextPane txtmat41;
    private javax.swing.JTextPane txtmat42;
    private javax.swing.JTextPane txtmat43;
    private javax.swing.JTextPane txtmat44;
    private javax.swing.JTextPane txtmat45;
    private javax.swing.JTextPane txtmat46;
    private javax.swing.JTextPane txtmat47;
    private javax.swing.JTextPane txtmat51;
    private javax.swing.JTextPane txtmat52;
    private javax.swing.JTextPane txtmat53;
    private javax.swing.JTextPane txtmat54;
    private javax.swing.JTextPane txtmat55;
    private javax.swing.JTextPane txtmat56;
    private javax.swing.JTextPane txtmat57;
    private javax.swing.JTextPane txtmat61;
    private javax.swing.JTextPane txtmat62;
    private javax.swing.JTextPane txtmat63;
    private javax.swing.JTextPane txtmat64;
    private javax.swing.JTextPane txtmat65;
    private javax.swing.JTextPane txtmat66;
    private javax.swing.JTextPane txtmat67;
    private javax.swing.JTextPane txtmat71;
    private javax.swing.JTextPane txtmat72;
    private javax.swing.JTextPane txtmat73;
    private javax.swing.JTextPane txtmat74;
    private javax.swing.JTextPane txtmat75;
    private javax.swing.JTextPane txtmat76;
    private javax.swing.JTextPane txtmat77;
    private javax.swing.JTextPane txtmat81;
    private javax.swing.JTextPane txtmat82;
    private javax.swing.JTextPane txtmat83;
    private javax.swing.JTextPane txtmat84;
    private javax.swing.JTextPane txtmat85;
    private javax.swing.JTextPane txtmat86;
    private javax.swing.JTextPane txtmat87;
    private javax.swing.JTextPane txtmat91;
    private javax.swing.JTextPane txtmat92;
    private javax.swing.JTextPane txtmat93;
    private javax.swing.JTextPane txtmat94;
    private javax.swing.JTextPane txtmat95;
    private javax.swing.JTextPane txtmat96;
    private javax.swing.JTextPane txtmat97;
    // End of variables declaration//GEN-END:variables
}
